"""add user columns

Revision ID: 37dc0fd08481
Revises: 057f56d965bc
Create Date: 2023-05-24 14:38:01.497100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils


STATUS = [
    ('Void', 'Void'),
    ('Active', 'Active'),
    ('Pending Approval', 'Pending Approval'),
    ('POW Approved', 'POW Approved'),
    ('POW Rejected', 'POW Rejected'),
    ('Pending Graduation', 'Pending Graduation'),
    ('Graduation Approved', 'Graduation Approved'),
    ('Graduation Rejected', 'Graduation Rejected'),
    ('Graduated', 'Graduated'),
]

# revision identifiers, used by Alembic.
revision = '37dc0fd08481'
down_revision = '057f56d965bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('term', sa.Column('first_day_class', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('secondary_email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
    op.add_column('user', sa.Column('linkedin', sqlalchemy_utils.types.url.URLType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'linkedin')
    op.drop_column('user', 'secondary_email')
    op.drop_column('term', 'first_day_class')

    # ### end Alembic commands ###
